// Review-only inventory. Nothing in this directory is imported by the screensaver.
export const references = [
  {
    id: 'R1',
    title: 'Engineering / long-range scan',
    elements: [
      'Two long gold title rails: rounded outer caps, inset elbow, title knock-out, narrow separators and terminal ticks.',
      'Left command bank: paired short capsules, right-aligned codes, large amber numbers between smaller cells, and unequal row lengths.',
      'Lower-left radial control: multiple concentric segmented rings, unequal angular sectors, numbered wedges, a divided blue center, cardinal tabs and a large truncated sector.',
      'Bracketed red energy signature: thin symmetric vertical lines with a diamond-shaped envelope; multicolor corner/side frame.',
      'Tall two-column structural spine with unequal stacked blocks, right-aligned small labels, nested opposing elbows and paired horizontal buses.',
      'Dense multi-column number banks, mixed digit lengths, grouped rows and color changes within a bank.',
      'Large scan title and parameter subtitle with a two-by-three cluster of capsule controls.',
      'Large rectangular two-dimensional star map: blue grid, faint point field, tick labels, large coordinate readouts, compact coordinate stacks and two segmented target brackets.',
      'Vertical scan commands at the map edge; compact stacked controls and data tiles around the main spine.',
    ],
    families: [
      'radial',
      'space-map',
      'reticle',
      'signature',
      'numbers',
      'metrics',
      'controls',
      'navigation',
      'elbow',
      'bus',
      'bracket',
      'heading',
      'codes',
    ],
  },
  {
    id: 'R2',
    title: 'Long-range scan / boundary map',
    elements: [
      'Red symmetric energy signature in a small bracketed viewport; multicolor side segments with exposed black breaks.',
      'Unequal stacked blue/cyan/ochre blocks, three-row paired capsule banks, numeric-only narrow columns and small right-aligned codes.',
      'Two nested elbows sharing a spine, twin segmented crossbars and a vertical scan-command list.',
      'Large right-aligned title and smaller scan-parameter line; two rows of three pill selectors.',
      'Two-dimensional point field on a blue Cartesian grid; warm and cool points indicate different sides of a region.',
      'Curved white boundary with dense perpendicular ticks; blue filled territory, spaced three-line region label, and a sharp diagonal entry into the curve.',
      'Screenshot checkerboard at the bottom is a transparency/export artifact, not a console component.',
    ],
    families: [
      'signature',
      'bracket',
      'codes',
      'controls',
      'numbers',
      'elbow',
      'bus',
      'navigation',
      'heading',
      'space-map',
      'boundary',
    ],
  },
  {
    id: 'R3',
    title: 'System 47 / diagnostic console',
    elements: [
      'Broad top and bottom elbows with a metallic light sweep, cropped inner opening, small detached cap and large title. Material treatment differs from the flat references.',
      'Left diagnostic register combines short colored bars, tiny square separators, oversized numeric values, short alphanumeric labels and deliberately dim/inactive rows.',
      'Upper numeric banks: tightly aligned columns of variable-length numbers; a central square-dot column; multiple semantic colors.',
      'Opposing central gold and lavender elbows; double thin crossbars; rectangular slider/bridge marker over the line.',
      'Large code/version plaque in a solid vertical block, plus readiness heading and a stacked paired-value register.',
      'Small framed technical plot: grid, vertical markers, curved response trajectories, horizontal trace fragments, square sample marker and large numeric caption beneath.',
      'Lower floating readout groups: square status ticks beside numbers and three compact horizontal value bars with detached end squares.',
      'Visible source watermark is not interface content to reproduce.',
    ],
    families: [
      'elbow',
      'heading',
      'metrics',
      'numbers',
      'status',
      'bus',
      'codes',
      'controls',
      'curve',
      'schematic',
      'bracket',
    ],
  },
  {
    id: 'R4',
    title: 'Animated engineering core (GIF)',
    elements: [
      'Six frames, 0.2 seconds each, form a 1.2-second loop. This is the only supplied reference whose motion can be directly observed.',
      'Large enclosing C-frame, upper-right auxiliary elbow, and lower partial frame; segmented label blocks share straight rail edges.',
      'Vector engine assembly: central vertical axis, paired rounded containment cells, flared ribbed end caps, central circular chamber, and collar struts.',
      'Right-angle energy conduit with rounded bend, alternating light/dark bands and a coupling from the core to an auxiliary assembly.',
      'Auxiliary manifold: two rows of four vertical capsules with horizontal clamps, small connecting neck and outer terminal bars.',
      'Several numeric banks with circular indicator bullets; unit-bearing technical heading and variable-length grouped values.',
      'Three compact output readouts combining a capsule end, a rectangular code cell and an oversized number.',
      'Bottom command strip with paired labels, thin separators, aligned control cells and truncated left-edge rail codes.',
      'Bottom timing matrix: five rows of discrete violet/black cells, thin grid, upper ruler ticks and taller red cursor marks.',
      'Observed motion: containment/manifold cell colors alternate; conduit highlights travel; numerical rows disappear and repopulate in groups; timing-matrix occupancy changes. The frame geometry stays fixed.',
    ],
    families: [
      'engine',
      'conduit',
      'manifold',
      'numbers',
      'status',
      'metrics',
      'controls',
      'elbow',
      'bus',
      'matrix',
      'codes',
      'heading',
    ],
  },
  {
    id: 'R5',
    title: 'LCARS Ultra / information panel',
    elements: [
      'Large red vertical-bar energy signature with a symmetric stepped envelope, in a four-corner multicolor bracket frame.',
      'Paired and staggered capsule/rectangular command banks with shared seams and short codes.',
      'Four status messages, each introduced by a small colored oval; states are written out as words.',
      'Two-column structural spine with uneven-height cells, identifiers, opposing elbows and twin segmented top buses.',
      'Large right-aligned online status/title, widely separated capsule commands, page title, secondary headline and narrow condensed paragraph.',
      'Nested lower return frame: long upper rule, inner rounded right corner, stacked right-side code blocks, shorter bottom rail, centered two-line attribution area.',
      'Visible web-template credit and placeholder prose are source content, not reusable console components.',
    ],
    families: [
      'signature',
      'bracket',
      'controls',
      'status',
      'codes',
      'elbow',
      'bus',
      'heading',
      'text',
    ],
  },
  {
    id: 'R6',
    title: 'Viewer / library dual workstation',
    elements: [
      'Two neighboring mirrored C-frames with adjacent central vertical rails, rounded exposed ends, title interruptions and unequal bottom bars.',
      'Window title strips with small MAX / MIN / CLOSE control cells and short separators.',
      'Astronomical image viewport: pale corner brackets, overlaid measurement grid, rectangular selection reticle, descriptive caption and zoom readout.',
      'Inner-edge viewer/navigation tools: narrow indicator ticks, large numbers, labeled rectangular cells; two task groups divided by a gap.',
      'File-library table: filename, size, type and modified date; compact aligned rows, highlighted selected filename, small open marker and a vertical scrollbar thumb.',
      'Small capsule action buttons beneath each pane: Options, New folder and File info.',
      'Bottom desktop/task strip separated by a fine rule; launch capsule, segmented Control/Security tabs and a right-aligned clock.',
      'The astronomical photograph is content inside the viewer, not a vector component; review specimens use an original synthetic star field instead.',
    ],
    families: [
      'elbow',
      'heading',
      'controls',
      'viewer',
      'reticle',
      'navigation',
      'metrics',
      'register',
      'taskbar',
      'bracket',
    ],
  },
];

// Five deliberate structural alternatives per family; palette is an independent choice.
const definitions = [
  [
    'radial',
    'Instruments',
    'Segmented radial interfaces',
    'Numbered annular sectors, central partitions and asymmetric cutaways; not a generic progress ring.',
    ['R1'],
    [
      ['Sector wheel', 'Three unequal rings with a cutaway quadrant and numbered wedges.'],
      ['Course fan', 'A semicircular command fan with paired bearing scales.'],
      ['Quadrant director', 'Four separated angular control banks around a divided hub.'],
      ['Offset analyzer', 'An eccentric inner dial with a broad outer readout sector.'],
      ['Split azimuth', 'Two opposing arc banks around a crosshair and linear readout.'],
    ],
  ],
  [
    'space-map',
    'Instruments',
    'Two-dimensional space maps',
    'Gridded point fields with map coordinates, target annotations and distinct spatial arrangements.',
    ['R1', 'R2'],
    [
      ['Sector survey', 'Cartesian star field with an outlined survey rectangle.'],
      ['Transit corridor', 'A slanted navigation corridor connects labeled waypoints.'],
      ['Binary neighborhood', 'Two local systems with orbital extents on one coordinate grid.'],
      ['Sensor mosaic', 'Four differently sampled survey quadrants share a coordinate frame.'],
      ['Deep-field chart', 'A dense field with a magnified inset and selection connector.'],
    ],
  ],
  [
    'boundary',
    'Instruments',
    'Region boundaries & map overlays',
    'Territory fills, curved ticked borders, region labels and exclusion shapes.',
    ['R2'],
    [
      ['Curved frontier', 'One continuous arc divides two survey regions.'],
      ['Diagonal corridor', 'Parallel ticked edges define a transit lane.'],
      ['Exclusion ellipse', 'A hatched elliptical perimeter surrounds a restricted sector.'],
      ['Stepped frontier', 'Orthogonal region steps alternate with measurement ticks.'],
      ['Nested range fronts', 'Three offset curved fronts divide named bands.'],
    ],
  ],
  [
    'reticle',
    'Instruments',
    'Target & selection reticles',
    'Open corners, crosshairs, segmented edges, sample markers and coordinate tags.',
    ['R1', 'R6'],
    [
      ['Bracket lock', 'Four broken corners with a small central aim point.'],
      ['Annular lock', 'Separated arcs surround cardinal markers.'],
      ['Dual tracking', 'Two linked brackets with a distance baseline.'],
      ['Window selection', 'Rectangular crop handles and dimension rulers.'],
      ['Triangulation', 'Three reference bearings meet at a polygonal target gate.'],
    ],
  ],
  [
    'engine',
    'Instruments',
    'Vector engine assemblies',
    'Containment cells, axial chambers, collars and flared end caps form a mechanical diagram.',
    ['R4'],
    [
      ['Axial core', 'A vertical stack of split cells and ribbed flared caps.'],
      ['Twin core', 'Two linked vertical chambers share a central coupling.'],
      ['Horizontal drive', 'A longitudinal engine with nozzle, manifold and field rings.'],
      ['Toroidal chamber', 'A ring-shaped engine with radial injectors and two feed lines.'],
      ['Three-stage reactor', 'Three different chamber sizes joined by narrowed throats.'],
    ],
  ],
  [
    'conduit',
    'Instruments',
    'Energy conduits & routes',
    'Thick orthogonal pipes, elbows, joints and directional energy packets.',
    ['R4'],
    [
      ['Single elbow', 'A right-angle transfer line with a large smooth bend.'],
      ['Split distribution', 'One inlet branches into three independently labeled outlets.'],
      ['Return loop', 'Two parallel lines connect in a rounded recirculation loop.'],
      ['Cross-junction', 'Four routes meet at an isolated central junction.'],
      ['Stepped transfer', 'A two-elbow stair route with inline coupling blocks.'],
    ],
  ],
  [
    'manifold',
    'Instruments',
    'Auxiliary manifolds & cell arrays',
    'Clamped capsule assemblies and banks of small containment cells.',
    ['R4'],
    [
      ['Paired capsule rack', 'Two rows of four cells with external clamps.'],
      ['Circular injector', 'Eight capsule injectors arranged around a hub.'],
      ['Linear exchanger', 'A long horizontal rack with alternating narrow and wide cells.'],
      ['Three-bank manifold', 'Three short racks connect to one distribution spine.'],
      [
        'Stacked reservoir',
        'Three vertical cells of unequal height with shared upper and lower buses.',
      ],
    ],
  ],
  [
    'signature',
    'Instruments',
    'Energy wave signatures',
    'Symmetric vertical strokes shaped into an energy envelope, with calibrated baselines.',
    ['R1', 'R2', 'R5'],
    [
      ['Diamond pulse', 'A sharply peaked symmetric envelope of evenly spaced strokes.'],
      ['Twin-lobe pulse', 'Two energy lobes separated by a narrow null.'],
      ['Damped burst', 'Large leading energy decays into a narrow tail.'],
      ['Carrier modulation', 'A rippling envelope around a dense high-frequency carrier.'],
      ['Split-band signature', 'Two independently scaled signatures occupy stacked channels.'],
    ],
  ],
  [
    'curve',
    'Instruments',
    'Technical curves & response plots',
    'Curved trajectories, partial traces, grid markers and numeric captions.',
    ['R3'],
    [
      ['Transfer response', 'Rising and falling curves cross at a sample marker.'],
      ['Damped response', 'Oscillations settle toward a steady reference.'],
      ['Phase portrait', 'A closed phase trajectory with orthogonal calibration marks.'],
      ['Three-channel trace', 'Three separated traces share one time ruler.'],
      ['Threshold sweep', 'A staircase response and smooth curve cross threshold bands.'],
    ],
  ],
  [
    'matrix',
    'Instruments',
    'Timing & occupancy matrices',
    'Discrete filled cells, dark vacancies, row identities and timing cursor marks.',
    ['R4'],
    [
      ['Five-track sequencer', 'Five horizontal bit tracks with a moving playhead.'],
      ['Resource lattice', 'A square occupancy grid with row and column addresses.'],
      ['Staggered allocation', 'Offset runs of occupied cells in variable-length rows.'],
      ['Mirrored memory', 'Two banks share a narrow central address spine.'],
      ['Diagonal propagation', 'A diagonal activation front crosses a rectangular lattice.'],
    ],
  ],
  [
    'numbers',
    'Data',
    'Dense technical number banks',
    'Tightly aligned numerical columns, variable digit lengths, color-coded groups and punctuated markers.',
    ['R1', 'R2', 'R3', 'R4', 'R5'],
    [
      ['Column telemetry', 'Six aligned columns of mixed-length values.'],
      ['Bullet blocks', 'Three dense groups with circular row indicators.'],
      ['Paired registers', 'Two number banks separated by a square-marker spine.'],
      ['Address / payload', 'Short addresses precede long fixed-width payloads.'],
      ['Sparse diagnostic', 'Dense rows with deliberate vacancies and highlighted sample bands.'],
    ],
  ],
  [
    'metrics',
    'Data',
    'Oversized numerical readouts',
    'Large values anchored to compact identifiers, units, bars and paired control cells.',
    ['R1', 'R3', 'R4', 'R6'],
    [
      ['Stacked instruments', 'Three large values with narrow unit columns.'],
      ['Value sandwich', 'Large central values sit between short colored label cells.'],
      ['Edge register', 'Values attach to a tall right-hand indicator rail.'],
      ['Split precision', 'Integer and fractional portions use different scales.'],
      ['Horizontal tally', 'Four compact readings share a segmented baseline.'],
    ],
  ],
  [
    'register',
    'Data',
    'Library & operations tables',
    'Compact multi-column records with a selected row, aligned metadata and a scrollbar.',
    ['R6'],
    [
      ['File library', 'Filename, size, type and modified date columns.'],
      ['Observation log', 'Timestamp, sector, magnitude and status columns.'],
      ['Engineering register', 'Assembly, output, tolerance and readiness columns.'],
      ['Transit manifest', 'Route, cargo, destination and arrival columns.'],
      ['Signal archive', 'Channel, frequency, duration and quality columns.'],
    ],
  ],
  [
    'status',
    'Data',
    'Status lights & readiness lists',
    'Small oval or square indicators paired with explicit state text; dim inactive rows.',
    ['R3', 'R4', 'R5'],
    [
      ['Oval annunciators', 'Four colored ovals introduce readable status sentences.'],
      ['Square ladder', 'Square ticks align beside compact system codes.'],
      ['Paired readiness', 'Two columns compare primary and reserve conditions.'],
      ['Segmented status strip', 'A continuous row of named system states.'],
      ['Priority stack', 'An expanded warning row interrupts smaller nominal rows.'],
    ],
  ],
  [
    'controls',
    'Controls',
    'Capsule & segmented command banks',
    'Task groups combine half-round ends, rectangular inner cells, paired rows and staggered lengths.',
    ['R1', 'R2', 'R3', 'R4', 'R5', 'R6'],
    [
      ['Paired banks', 'Three rows split into two touching command cells.'],
      ['Six-selector cluster', 'Two rows of three independent capsules.'],
      ['Stepped actions', 'Unequal row lengths create an inset command stack.'],
      ['Continuous command bar', 'Five inner cells share a single rounded outer silhouette.'],
      ['Grouped toolbar', 'Two small banks separated by a task-sized gap.'],
    ],
  ],
  [
    'navigation',
    'Controls',
    'Rail tools & numeric commands',
    'Narrow status ticks, large numbers and short rectangular tool labels aligned to a spine.',
    ['R1', 'R2', 'R6'],
    [
      ['Viewer tools', 'Zoom and rotate tools with oversized shortcut numbers.'],
      ['Scan parameters', 'A continuous stack of short scan-command cells.'],
      ['Mirrored tool rails', 'Two inward-facing tool banks flank an open center.'],
      ['Indexed operations', 'Four ascending indices pair with long operation labels.'],
      ['Split task rail', 'Two command groups separated within one vertical run.'],
    ],
  ],
  [
    'elbow',
    'Structure',
    'Elbows, returns & enclosing frames',
    'Smooth inner/outer tangents, matched rail widths, opposing curves and uniform black seams.',
    ['R1', 'R2', 'R3', 'R4', 'R5', 'R6'],
    [
      ['Single C-frame', 'A left rail joins broad top and narrow bottom returns.'],
      ['Opposing nested elbows', 'Two reversed elbows share an aligned spine.'],
      ['Twin inward frames', 'Mirrored enclosures meet at a central double rail.'],
      ['Asymmetric return', 'A short upper elbow and long lower return define an open console.'],
      ['Offset double frame', 'A main frame and smaller inset return form an offset assembly.'],
    ],
  ],
  [
    'bus',
    'Structure',
    'Segmented bars & bridge markers',
    'Parallel data buses, uneven block lengths, terminal ticks and rectangular coupling/slider markers.',
    ['R1', 'R2', 'R3', 'R4', 'R5'],
    [
      ['Double data bus', 'Two segmented rows with alternating long and short blocks.'],
      ['Coupling bridge', 'A rectangular bridge interrupts two continuous lines.'],
      ['Indexed ribbon', 'Numbered blocks carry an aligned lower calibration rule.'],
      ['Terminal ladder', 'Thin rails end in detached vertical terminal ticks.'],
      ['Split distribution bar', 'A thick bus branches into two finer tracks.'],
    ],
  ],
  [
    'bracket',
    'Structure',
    'Instrument frames & corner brackets',
    'Open multicolor corners, segmented side edges and clipped inner windows.',
    ['R1', 'R2', 'R3', 'R5', 'R6'],
    [
      ['Four open corners', 'Four isolated quarter-round corners define a viewport.'],
      ['Segmented side rails', 'Colored rail segments flank an open plot.'],
      ['Inset monitor', 'A thick instrument surround carries a numeric lower caption.'],
      ['Wide slit viewport', 'Shallow long frame with separately colored end caps.'],
      ['Offset corner gate', 'Unequal corner lengths mark an asymmetric instrument field.'],
    ],
  ],
  [
    'schematic',
    'Instruments',
    'Technical line schematics',
    'Orthogonal trace fragments, sample markers and vector line assemblies inside diagnostic views.',
    ['R3'],
    [
      ['Bus schematic', 'Branches connect a central bus to four labeled modules.'],
      ['Thermal exchanger', 'Interleaved coil paths link inlet and outlet collectors.'],
      ['Sensor geometry', 'Three sensor baselines triangulate a central assembly.'],
      ['Circuit routing', 'Angular tracks link square nodes across a measured field.'],
      ['Layer cross-section', 'Five thin strata surround a central probe and callouts.'],
    ],
  ],
  [
    'viewer',
    'Content',
    'Scientific image viewers',
    'Framed content window, grid overlay, selected region, zoom caption and inset detail.',
    ['R6'],
    [
      ['Deep-field viewer', 'Synthetic point field with a rectangular region selection.'],
      ['Spectral plate', 'False-color sample field with a vertical measurement cursor.'],
      ['Survey tiles', 'Four synthetic image tiles with a highlighted tile.'],
      ['Magnified sample', 'Overview field paired with an enlarged selected detail.'],
      ['Strip scan', 'A wide image strip with two tracked samples and a scale ruler.'],
    ],
  ],
  [
    'heading',
    'Structure',
    'Title & window identity strips',
    'Large condensed titles interrupt rails; window controls, subtitles and codes establish hierarchy.',
    ['R1', 'R2', 'R3', 'R5', 'R6'],
    [
      ['Title interruption', 'Large system name breaks a long rounded rail.'],
      ['Viewer titlebar', 'Window title and three compact window-action cells.'],
      ['Right-aligned station', 'Station title sits above a smaller parameter line.'],
      ['Two-level identity', 'Main system heading and a long secondary section band.'],
      ['Split-pane headers', 'Two named panes share one segmented header axis.'],
    ],
  ],
  [
    'taskbar',
    'Controls',
    'Desktop strips & clocks',
    'Bottom rules, launch capsules, task tabs, security labels and right-aligned time.',
    ['R6'],
    [
      ['Classic task strip', 'Launch, two segmented task tabs and a large clock.'],
      ['Docked session bar', 'Three compact session cells follow a clock capsule.'],
      ['Mirrored controls', 'Launch and security sit at opposite ends around a centered time.'],
      ['Two-level task rail', 'A slim status rule floats over the active task bank.'],
      ['Compact clock dock', 'Clock and date block anchor a short stack of task selectors.'],
    ],
  ],
  [
    'text',
    'Content',
    'Information & instruction panels',
    'Condensed headline, short prose, caption area and nested return-rule treatment.',
    ['R5'],
    [
      ['Briefing panel', 'Title, explanatory paragraph and a short footer rule.'],
      ['Procedure steps', 'Three numbered operating instructions with aligned labels.'],
      ['Two-column note', 'System note paired with a compact reference column.'],
      ['Readiness notice', 'Large readiness heading above a concise explanation.'],
      [
        'Captioned report',
        'A report heading, measured text lines and a two-line attribution area.',
      ],
    ],
  ],
  [
    'codes',
    'Data',
    'Code plaques & stacked ID blocks',
    'Unequal solid color fields, small edge-aligned identifiers and large version/coordinate plaques.',
    ['R1', 'R2', 'R3', 'R4', 'R5'],
    [
      ['Tall identity stack', 'Four unequal block heights with corner-aligned codes.'],
      ['Version plaque', 'One large code plate with a secondary version line.'],
      ['Twin code columns', 'Two columns alternate short and tall labeled cells.'],
      ['Coordinate slabs', 'Three wide slabs pair a large coordinate with a tiny suffix.'],
      ['Detached register', 'Floating label blocks pair with isolated terminal squares.'],
    ],
  ],
  [
    'layout-scan',
    'Layouts',
    'Nested scanner / shared spine',
    'A utility column and tall segmented spine join shallow upper telemetry to a dominant lower map through opposing elbows.',
    ['R2', 'R5'],
    [
      [
        'Classic nested scan',
        '22% utility, 14% spine, 64% content; shallow header over a deep map.',
      ],
      ['Right-hand spine', 'Mirrored utility and spine with the large map on the left.'],
      [
        'Expanded telemetry',
        'Upper numeric region grows to 38%; the map retains the larger lower region.',
      ],
      ['Narrow utility', 'A 15% utility strip gives more width to the primary map.'],
      [
        'Inset scan station',
        'The lower map gets an additional internal return and side command strip.',
      ],
    ],
  ],
  [
    'layout-radial',
    'Layouts',
    'Radial instrument / large map',
    'A radial lower-left instrument balances a large lower-right map beneath a continuous top telemetry band.',
    ['R1'],
    [
      ['Engineering survey', 'Left radial and numeric column, central spine, dominant right map.'],
      ['Radial priority', 'A larger left instrument takes 42% of the lower screen.'],
      ['Upper radial station', 'Radial moves above the left register while the map stays tall.'],
      ['Mirrored survey', 'Large map moves left; radial, signature and controls stack at right.'],
      [
        'Wide map / shallow bank',
        'A panoramic lower map sits beneath a radial-and-data upper tier.',
      ],
    ],
  ],
  [
    'layout-diagnostic',
    'Layouts',
    'Diagnostic register / nested plot',
    'An enclosing return frame holds a left numeric register, upper dense banks and lower diagnostics with a small technical plot.',
    ['R3'],
    [
      ['System diagnostic', 'Outer C-frame, left register, upper banks, lower register and plot.'],
      ['Plot emphasis', 'The lower technical plot doubles in width beside a short register.'],
      ['Register emphasis', 'Tall numeric register occupies 34%; diagrams remain subordinate.'],
      ['Mirrored diagnostic', 'Outer return and register move right; plots and banks align left.'],
      ['Stacked diagnostics', 'Two compact plots occupy a lower strip beneath one wide data bank.'],
    ],
  ],
  [
    'layout-engineering',
    'Layouts',
    'Engineering schematic / lower timeline',
    'A large upper C-frame surrounds engine, readouts and auxiliary plant; an independent shallow lower frame holds a timing matrix.',
    ['R4'],
    [
      [
        'Core and timeline',
        'Upper engine stage occupies 72%; a lower matrix is a separate framed band.',
      ],
      ['Wide engine', 'Horizontal drive spans the upper center, with side diagnostics.'],
      [
        'Tall timeline',
        'Lower matrix grows to 32%; auxiliary plant shifts beside the compact core.',
      ],
      ['Twin-core plant', 'Two engine columns share the upper frame and one side manifold.'],
      [
        'Mirrored service plant',
        'Core and conduits reverse direction; number banks remain outside the flow path.',
      ],
    ],
  ],
  [
    'layout-information',
    'Layouts',
    'Utility sidebar / information frame',
    'A small signature and control sidebar sit beside a segmented spine, shallow title region and large open text field with an inset return.',
    ['R5'],
    [
      ['Classic information', 'Signature, actions and states at left; title and text at right.'],
      ['Mirrored information', 'The utility stack moves right; the main reading field opens left.'],
      ['Compact utility', 'A narrow sidebar leaves a broad information field.'],
      [
        'Tall title region',
        'Upper status and commands gain height; the lower text area stays one uninterrupted field.',
      ],
      [
        'Split reference note',
        'A main briefing and narrow reference column share the lower return frame.',
      ],
    ],
  ],
  [
    'layout-workstation',
    'Layouts',
    'Mirrored viewer / library workstation',
    'Two adjacent C-frames face inward around a central double tool rail; a separate desktop task strip anchors the bottom.',
    ['R6'],
    [
      ['Balanced workstation', 'Equal viewer and library panes with central opposing tools.'],
      ['Viewer emphasis', 'Viewer occupies 62%; compact library takes the remaining width.'],
      ['Library emphasis', 'Library occupies 62%; narrow viewer preserves the selection tool.'],
      [
        'Unequal vertical panes',
        'A tall viewer sits beside a shorter library and metadata footer.',
      ],
      [
        'Stacked workstation',
        'Two full-width panes stack vertically with their own short tool rails.',
      ],
    ],
  ],
];
export const families = definitions.map(([id, group, title, description, refs, variants], i) => ({
  id,
  group,
  title,
  description,
  refs,
  prefix: `E${String(i + 1).padStart(2, '0')}`,
  variants: variants.map(([name, difference], v) => ({
    id: `E${String(i + 1).padStart(2, '0')}-${String(v + 1).padStart(2, '0')}`,
    name,
    difference,
  })),
}));
export const variantCount = families.reduce((sum, f) => sum + f.variants.length, 0);
